name: 'Chromatic Storybook Deployment'

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.working-directory }}
      - name: Generate Environment Variables File for Production
        run: |
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env.production
        working-directory: ${{ env.working-directory }}
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
